### ISSUE TITLE
Training/testing on any dataset

### ISSUE THREAD

**Issue by Thomas-Mccabe** [visinf/self-mono-sf#1]
Hi, this is a really interesting project! Will there be code for running this network on any dataset for testing and training? If not, how would you recommend approaching this? 

Cheers

**Comment by hurjunhwa** [comment]
Hi, 

Thanks a lot!
For training/testing on any dataset, you can simply write the dataloader for your dataset like here:
`https://github.com/visinf/self-mono-sf/blob/master/datasets/kitti_raw_monosf.py`

Then, you need to include your dataloader here:
`https://github.com/visinf/self-mono-sf/blob/master/datasets/__init__.py`
and then you are able to call your dataloader in the script file:
`Train_Dataset` 
in `https://github.com/visinf/self-mono-sf/blob/master/scripts/train_monosf_selfsup_kitti_raw.sh`

Best,
Jun

**Comment by TengFeiHan0** [comment]
@hurjunhwa I'm going to test your pre-trained models on my own monocular dataset. However, I found your code only works for the stereo kitti dataset, Is it necessary to compute the camera [intrinsics](https://github.com/visinf/self-mono-sf/blob/master/datasets/kitti_2015_test.py#L67)?  If I only could provide monocular images and its intrinsic, Is it possible to run your code?

**Comment by hurjunhwa** [comment]
@TengFeiHan0 

Hi, the right-view images are included only for training/fine-tuning in the dataloader.
And of course in the testing time, it only requires two monocular images + intrinsics.
You may write your own dataloader that passes those dictionary keys into the augmentation module and network modules: ``"input_l1", "input_l2", "input_k_l1", "input_k_l2", and "input_size"``.
Here, ``input_k_l1`` and ``input_k_l2`` are the camera intrinsics at time t and t+1, which basically are the same.

Best,
Jun
