### ISSUE TITLE
sf=0.0000 during scene flow test

### ISSUE THREAD

**Issue by NIRVANALAN** [visinf/self-mono-sf#10]
Hi,
after executing the evaluation script ```./eval_monosf_finetune_kitti_test.sh```, the tqdm output keep printing```sf=0.0000```.
![image](https://user-images.githubusercontent.com/23359323/94391624-885e6600-0188-11eb-9ee5-c882156ce970.png)

But the depth evaluation works well. Any suggestions?

**Comment by thanhmvu** [comment]
I also got this output and found out that it's because the SF loss is set to 0 here for some reason, but I'm not sure why.

https://github.com/visinf/self-mono-sf/blob/c31a1d25cd04b3396056877ace591695002b232a/losses.py#L492

**Comment by hurjunhwa** [comment]
Hi, 

The script ``./eval_monosf_finetune_kitti_test.sh`` outputs the images for uploading in the official KITTI benchmark.
As no ground truth available, it doesn't evaluate the results on your local machine, and I just set the loss zero (which has no meaning.)

As depth ground truth is available (for both KITTI or Eigen split), the scripts for the depth evaluation give the results.

**Comment by NIRVANALAN** [comment]
> Hi,
> 
> The script `./eval_monosf_finetune_kitti_test.sh` outputs the images for uploading in the official KITTI benchmark.
> As no ground truth available, it doesn't evaluate the results on your local machine, and I just set the loss zero (which has no meaning.)
> 
> As depth ground truth is available (for both KITTI or Eigen split), the scripts for the depth evaluation give the results.

Thanks for your reply!
