### ISSUE TITLE
Data Directory structure?

### ISSUE THREAD

**Issue by SwagJ** [visinf/self-mono-sf#12]
Thank you for this great work! 
I am a bit confused on the data directory structure for running experiment. Is this the same as that in MonoDepth?
 https://github.com/OniroAI/MonoDepth-PyTorch#dataloader

I am looking forward to your reply. 
Thank you!

**Comment by hurjunhwa** [comment]
Hi,
Thanks!
We didn't modify from the original structure of the KITTI raw dataset (http://www.cvlibs.net/datasets/kitti/raw_data.php)
It will be like:
```
(Input data path in the script file)
├── 2011_09_26
│   ├── 2011_09_26_drive_0001_sync
│   │   ├── image_02
│   │   │   ├─ data
│   │   │   │   ├── 0000000000.png
│   │   │   │   └── ...
│   │   ├── image_03
│   │   │   ├── data
│   │   │   │   ├── 0000000000.png
│   │   │   │   └── ...
│   ├── ...
├── 2011_09_28
├── 2011_09_29
└── ...
```
Best,
Jun

**Comment by SwagJ** [comment]
Thank you very much for your swift reply! It is super clear!

Best,
