### ISSUE TITLE
Proble while processing Visualization 

### ISSUE THREAD

**Issue by doublexushuang** [visinf/self-mono-sf#14]
@hurjunhwa
Hi ! Thanks for your great work for the visualization code of scene flow!
But it seems that I've got one problem with it.
![image](https://user-images.githubusercontent.com/81733735/117532844-228a6480-b01c-11eb-91a2-4d10bf7c9b07.png)

As you may see in the picture, I didn't change any of the data except for the three directories:kitti_data_dir, result_dir, vis_dir
I want to know where the problem may occur.
Is it the path problem or is the installation version of open3d different?

**Comment by doublexushuang** [comment]
Solved this problem by uninstall open3d-0.12.0 and install open 3d-0.8.0.0

**Comment by doublexushuang** [comment]
Here comes another problem, the forty .png images created are all black (can't be seen at the vis folder)
![image](https://user-images.githubusercontent.com/81733735/117614802-6d7eb600-b19b-11eb-8028-e740dba7783b.png)

And the warning is shown in the figure below：
![image](https://user-images.githubusercontent.com/81733735/117615031-c0586d80-b19b-11eb-8799-200fbc1380ef.png)

**Comment by hurjunhwa** [comment]
Hi 
It can be also from using png >= 0.20.0, which I used the version 0.18.0. 
I will have a look and revise codes so that it can run with the up-to-date versions.

**Comment by doublexushuang** [comment]
Thanks! @hurjunhwa 
I don't clearly understand what is the PNG version you mentioned. Do you mean open3d?
Thank you very much for your willingness to update the code

**Comment by hurjunhwa** [comment]
Umm.. it‘s a pypng package for loading disparity and flow maps

**Comment by hurjunhwa** [comment]
Hi,
Can you try to pull the recent commit and try it again?
It works on open3d-0.12.0 and needs opencv (and doesn't use pypng any more).
First, please run it with the included example (KITTI 000139 sequence), and try it with your custom example.

**Comment by doublexushuang** [comment]
Sure! I'd love to!!!
 I've tried and the problems are gone as we expected. No Error or Warning.
But the .png images are still black. The visualized result can only be seen in open3d generated by Pycharm.
![image](https://user-images.githubusercontent.com/81733735/117752022-ab85e380-b248-11eb-9112-d9a011a4352e.png)

I still can't check the images  in vis folder.

![image](https://user-images.githubusercontent.com/81733735/117752359-3535b100-b249-11eb-8b0e-c2d8ff9314fe.png)

**Comment by hurjunhwa** [comment]
Then, it means that the image-saving function doesn't properly work or the code is not compatible with your local setting.
I changed it from matplotlib to scikit-image.
Could you try again with the recent commit?

**Comment by doublexushuang** [comment]
It seems not suitable for me. Here comes the warning and the image is still black.
`WARNING - 2021-05-12 11:14:08,080 - util - Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.`
So I changed the code to use the function img_as_ubyte to do the conversion.
`io.imsave(os.path.join(vis_dir, "{:06d}_{:02d}.png".format(save_id, glb.index)), img_as_ubyte(image))`
And a fundamental problem still exists.
`UserWarning: vis/000139_37.png is a low contrast image `
`warn('%s is a low contrast image' % fname)`
Which may mean that the generated image itself is black, and the problem is not in the saving of the image. 
Could this be the cause of the problem？
I'm a totally new hand in this area. I hope you can give the answer.
Thank you again for you help!!!

**Comment by hurjunhwa** [comment]
hmm.. then maybe you can print out the ```image``` by ```print(image)``` or ```print(img_as_ubyte(image))```, and check whether it's a 3-channel array which values range between 0 and 255.
If yes, then the problem is in the saving of the image.

**Comment by doublexushuang** [comment]
Unfortunately they are all zeros just like this.
![image](https://user-images.githubusercontent.com/81733735/118094499-6527b480-b401-11eb-93e1-efc0de560211.png)
So all images are certainlly black for RGB.
What is the probably reason?

**Comment by hurjunhwa** [comment]
I don’t know. 
it works well in my local setting, open3d 0.12.0 and running in the command line, not using pyCharm. 

Maybe you can follow each line and find which line of codes re-initializes the rendered image to the black one.

**Comment by doublexushuang** [comment]
Thanks a lot for all your advice!
 I'll try to solve the problem on my own. After I find the solution I'll comment here for others to follow.
