### ISSUE TITLE
Scaling in Augmentation

### ISSUE THREAD

**Issue by Bayrambai** [visinf/self-mono-sf#15]
Thanks for making your code open,

Can you tell me how do you obtain [0.93, 1] scaling for size [256, 832] in your Augmentation? Is scaling dependent on the resized image?

**Comment by hurjunhwa** [comment]
Hi,
The two parameters are independent.

You can intuitively think that (although the actual implementation is a bit different):
 - First, it generates an intermediate image by resizing with the random scale between [0.93, 1] + random rotation and translation)
 - and then it crops a rectangle with the size of [256. 832]

So, you can freely change the two parameters as you wish.
However, there is a stage that discards an invalid configuration such as when the intermediate image is smaller than the crop size. 
This kind of case will not be used for training.

**Comment by Bayrambai** [comment]
Thanks for your reply
