### ISSUE TITLE
About network architecture

### ISSUE THREAD

**Issue by 2020namemyself2020** [visinf/self-mono-sf#22]
I notice that for every layer except, the disparity is limited to 0-0.3 by “self.sigmoid(disp_l1) * 0.3”. Why is it designed this way？I know the ground truth of the disparity is limited to 0-1 by the function _read_png_disp_ in common.py. I think it may not be appropriate for other datasets such as Flyingthings3D because normalization is difficult to conduct as disparity is not between 0 and 255. If not normalization, will the result be worse?

**Comment by 2020namemyself2020** [comment]
Hello,sorry to interrupt you

**Comment by hurjunhwa** [comment]
The design choice follows the [MonoDepth paper](https://github.com/mrharicot/monodepth/blob/b76bee4bd12610b482163871b7ff93e931cb5331/monodepth_model.py#L124). The underlying idea is to let the network output the disparity between [0, 0.3 * image_width]. 

Yes, your point is absolutely right. The learned scale is only for the KITTI dataset and doesn't generalize to other datasets with different focal lengths. The estimation then would be only up to scale and/or up to shift.

**Comment by 2020namemyself2020** [comment]
Thanks for your explanation sincerely!
