### ISSUE TITLE
Question about projectSceneFlow2Flow function 

### ISSUE THREAD

**Issue by Debrove** [visinf/self-mono-sf#23]
Hi, I am very interested in your work!

I reimplemented your code on nuscenes and I noticed the [line 134](https://github.com/visinf/self-mono-sf/blob/master/utils/sceneflow_util.py#L134) in the function projectSceneFlow2Flow that the pixelgrid is not normalized. It makes the obtained flow to be big (absolute value), which results in a bad visualization. I really want to know whether it should be normalized. 

Looking forward to your reply. Thank you!

**Comment by hurjunhwa** [comment]
It might be due to [disp2depth_kitti](https://github.com/visinf/self-mono-sf/blob/eec356d95038da49e6705194e6dc0780b750f2b0/utils/sceneflow_util.py#L26) that the stereo baseline is explicitly set to KITTI. Have you considered changing this parameter for Nuscenes?

**Comment by Debrove** [comment]
Thanks for the quick reply!!!

I found the problem with my code. The "coord" in the projectSceneFlow2Flow function should not be normalized. Now I can visualize it with good results! Thanks!!
