### ISSUE TITLE
requirement.txt for packages

### ISSUE THREAD

**Issue by firattamur** [visinf/self-mono-sf#7]
Hello,

I am trying to run **train_monosf_selfsup_kitti_raw.sh** file but I have encountered an error. 

`No module named 'colorama'`

In the closed issues, I have seen that tqdm version causes a problem that's why I don't want to install needed packages without knowing which version you used. Could you provide a requirements.txt?

Thank you

**Comment by hurjunhwa** [comment]
Hi

I just pushed the ``requirement.txt`` file.
For these two packages (``forward-warp-cuda=0.0.0=pypi_0``, ``correlation-cuda=0.0.0=pypi_0``),
you can manually install them using ``install_modules.sh``.

Best,
Jun

**Comment by firattamur** [comment]
Great work thank you!
