### ISSUE TITLE
The link to Eigen Split Projected Depth is lost

### ISSUE THREAD

**Issue by minghanz** [visinf/self-mono-sf#9]
Hi, 

Thanks for sharing the great work. I found the link to the _Eigen Split Projected Depth_ for the monocular depth evaluation on the Eigen Split in the readme is not valid. Could you check it out and share a valid link to the depth data? Thanks!

**Comment by hurjunhwa** [comment]
Hi,

Thanks for letting me know.
Here is the preliminary link for the file.
https://drive.google.com/file/d/1a97lgOgrChkLxi_nvRpmbsKspveQ6EyD/view?usp=sharing
I will put the official link in the readme.
Thanks!
